/* Modell-Icons der Fokus-Hersteller: welches Katalog-Gerät welches Icon bekommt.
   Die SVGs liegen in assets/icons/devices und werden mit
   scripts/geraete-icons.js erzeugt. Die Regeln prüfen „Hersteller Modell“ von
   oben nach unten, die erste passende gewinnt. Geräte ohne Treffer behalten
   das Icon ihres Gerätetyps. */

export const MODELL_ICONS = {
  // key: [Hersteller, Bezeichnung im Icon-Auswahlmenü]
  ma3_full: ["MA Lighting", "grandMA3 full-size"],
  ma3_light: ["MA Lighting", "grandMA3 light"],
  ma3_compact_xt: ["MA Lighting", "grandMA3 compact XT"],
  ma3_compact: ["MA Lighting", "grandMA3 compact"],
  ma3_extension: ["MA Lighting", "grandMA3 extension"],
  ma3_replay: ["MA Lighting", "grandMA3 replay unit"],
  ma3_pu_m: ["MA Lighting", "grandMA3 processing unit M"],
  ma3_pu_l: ["MA Lighting", "grandMA3 processing unit L"],
  ma3_pu_xl: ["MA Lighting", "grandMA3 processing unit XL"],
  ma3_cmdwing_xt: ["MA Lighting", "grandMA3 command wing XT"],
  ma3_cmdwing: ["MA Lighting", "grandMA3 command wing"],
  ma3_faderwing: ["MA Lighting", "grandMA3 fader wing"],
  ma3_node2: ["MA Lighting", "grandMA3 2Port Node"],
  ma3_node4: ["MA Lighting", "grandMA3 4Port Node"],
  ma3_node8: ["MA Lighting", "grandMA3 8Port Node"],
  ma3_ionode: ["MA Lighting", "grandMA3 I/O Node"],
  ma_switch: ["MA Lighting", "MA Network Switch"],
  ma2_full: ["MA Lighting", "grandMA2 full-size"],
  ma2_light: ["MA Lighting", "grandMA2 light"],
  ma2_ultralight: ["MA Lighting", "grandMA2 ultra-light"],
  ma2_replay: ["MA Lighting", "grandMA2 replay unit"],
  ma2_cmdwing: ["MA Lighting", "grandMA2 command wing"],
  ma2_faderwing: ["MA Lighting", "grandMA2 fader wing"],
  ma2_node2: ["MA Lighting", "MA 2Port Node (grandMA2)"],
  ma2_node8: ["MA Lighting", "MA 4Port / 8Port Node (grandMA2)"],
  ma_npu: ["MA Lighting", "MA NPU"],
  ma_vpu: ["MA Lighting", "MA VPU"],
  ma_nsp: ["MA Lighting", "MA NSP"],
  ma1: ["MA Lighting", "grandMA (1)"],
  dot2_core: ["MA Lighting", "dot2 core"],
  dot2_wing: ["MA Lighting", "dot2 XL / Wing"],
  dot2_node4: ["MA Lighting", "dot2 Node4"],
  gc10: ["Luminex", "GigaCore 10"],
  gc16: ["Luminex", "GigaCore 12 / 14 / 16"],
  gc18: ["Luminex", "GigaCore 18t / 20t"],
  gc30: ["Luminex", "GigaCore 26i / 30i"],
  luminode1: ["Luminex", "LumiNode 1"],
  luminode2: ["Luminex", "LumiNode 2"],
  luminode4: ["Luminex", "LumiNode 4"],
  luminode12: ["Luminex", "LumiNode 12"],
  lumicore: ["Luminex", "LumiCore"],
  lumisplit: ["Luminex", "LumiSplit"],
  cisco_8: ["Cisco", "Switch 8 Ports (kompakt)"],
  cisco_16: ["Cisco", "Switch 16 Ports"],
  cisco_24: ["Cisco", "Switch 24 Ports"],
  cisco_48: ["Cisco", "Switch 48 Ports"],
  cisco_c1300_24p4x: ["Cisco", "Catalyst C1300-24P-4X"],
  cisco_9k: ["Cisco", "Catalyst 9200 / 9300"],
  cisco_meraki: ["Cisco", "Meraki MS"],
  cisco_ie: ["Cisco", "Catalyst IE (Hutschiene)"],
  cisco_ap: ["Cisco", "Access Point"],
  yam_rivage: ["Yamaha", "RIVAGE PM"],
  yam_cl: ["Yamaha", "CL5 / CL3 / CL1"],
  yam_ql: ["Yamaha", "QL5 / QL1"],
  yam_dm7: ["Yamaha", "DM7"],
  yam_dm3: ["Yamaha", "DM3"],
  yam_tf: ["Yamaha", "TF-Serie"],
  yam_rio: ["Yamaha", "Rio / RPio"],
  yam_tio: ["Yamaha", "Tio1608"],
  yam_ri8: ["Yamaha", "Ri8-D / Ro8-D"],
  yam_ruio: ["Yamaha", "RUio16-D"],
  yam_amp: ["Yamaha", "Endstufe (XMV, PC, NXAMP)"],
  yam_dsp: ["Yamaha", "DSP (MTX, MRX, DME)"],
  yam_swp: ["Yamaha", "SWP1 / SWP2"],
  yam_switch: ["Yamaha", "SWR / SWX"],
  sss_dpb: ["Schnick-Schnack-Systems", "DPB Pixel-Router"],
  sss_pixelgate: ["Schnick-Schnack-Systems", "Pixel-Gate"],
  sss_netzteil: ["Schnick-Schnack-Systems", "Systemnetzteil 4 / 4E"],
  sss_sysone: ["Schnick-Schnack-Systems", "Sys One"],
  sss_tile: ["Schnick-Schnack-Systems", "LED-Tile"],
  sss_strip: ["Schnick-Schnack-Systems", "LED-Strip / Profil"],
  dante_avio_xlr: ["Audinate", "Dante AVIO (XLR / AES3)"],
  dante_avio_usb: ["Audinate", "Dante AVIO USB"],
  dante_avio_bt: ["Audinate", "Dante AVIO Bluetooth"],
  dante_karte: ["Audinate", "Dante-Karte (Slot / PCIe)"],
  dante_modul: ["Audinate", "Dante-OEM-Modul"],
};

const REGELN = [
  // MA Lighting — grandMA3
  [/grandMA3 full-size/i, "ma3_full"],
  [/grandMA3 light/i, "ma3_light"],
  [/grandMA3 compact XT/i, "ma3_compact_xt"],
  [/grandMA3 compact/i, "ma3_compact"],
  [/grandMA3 extension/i, "ma3_extension"],
  [/grandMA3 replay/i, "ma3_replay"],
  [/grandMA3 processing unit XL/i, "ma3_pu_xl"],
  [/grandMA3 processing unit L/i, "ma3_pu_l"],
  [/grandMA3 processing unit M/i, "ma3_pu_m"],
  [/grandMA3 onPC command wing XT/i, "ma3_cmdwing_xt"],
  [/grandMA3 onPC command wing/i, "ma3_cmdwing"],
  [/grandMA3 onPC fader wing/i, "ma3_faderwing"],
  [/grandMA3 I\/O Node/i, "ma3_ionode"],
  [/grandMA3 .*\b2Port Node/i, "ma3_node2"],
  [/grandMA3 .*\b8Port Node/i, "ma3_node8"],
  [/grandMA3 .*\b4Port Node|grandMA3 xPort/i, "ma3_node4"],
  [/MA Network Switch/i, "ma_switch"],
  // grandMA2 und MA-Netzwerkgeräte
  [/grandMA2 full-size/i, "ma2_full"],
  [/grandMA2 light/i, "ma2_light"],
  [/grandMA2 ultra-light/i, "ma2_ultralight"],
  [/grandMA2 replay/i, "ma2_replay"],
  [/grandMA2 onPC command wing/i, "ma2_cmdwing"],
  [/grandMA2 fader wing/i, "ma2_faderwing"],
  [/MA NPU/i, "ma_npu"],
  [/MA VPU/i, "ma_vpu"],
  [/MA NSP/i, "ma_nsp"],
  [/MA Lighting MA 2Port Node/i, "ma2_node2"],
  [/MA Lighting MA [48]Port Node/i, "ma2_node8"],
  [/grandMA1|grandMA \(grandMA1\)/i, "ma1"],
  [/dot2 core/i, "dot2_core"],
  [/dot2 XL|dot2 .*wing/i, "dot2_wing"],
  [/dot2 Node4/i, "dot2_node4"],
  // Luminex
  [/GigaCore 10\b|GigaCore 10[it]/i, "gc10"],
  [/GigaCore 1[2-6]|GigaCore 14R/i, "gc16"],
  [/GigaCore (18|20)/i, "gc18"],
  [/GigaCore (26|30)/i, "gc30"],
  [/LumiNode 12/i, "luminode12"],
  [/LumiNode 4/i, "luminode4"],
  [/LumiNode 2|Ethernet-DMX2/i, "luminode2"],
  [/LumiNode 1/i, "luminode1"],
  [/Ethernet-DMX8/i, "luminode12"],
  [/LumiCore/i, "lumicore"],
  [/LumiSplit/i, "lumisplit"],
  // Cisco
  [/Cisco .*Meraki MS/i, "cisco_meraki"],
  [/Cisco .*(9120|Meraki MR)/i, "cisco_ap"],
  [/Cisco .*IE3300/i, "cisco_ie"],
  [/Cisco Catalyst 9[23]00/i, "cisco_9k"],
  [/Cisco .*-(8|10)[A-Z]*P?-|SG350-10|Cisco .*-8[A-Z]{1,3}-|C1300-12XT|2960-L/i, "cisco_8"],
  [/C1300X?-24F?P-4X/i, "cisco_c1300_24p4x"],
  [/Cisco .*-16/i, "cisco_16"],
  [/Cisco .*-(24|28)|Cisco .*SG350-28/i, "cisco_24"],
  [/Cisco .*-48/i, "cisco_48"],
  // Yamaha (auch NEXO)
  [/^Yamaha RIVAGE/i, "yam_rivage"],
  [/Yamaha CL5/i, "yam_cl"],
  [/Yamaha QL/i, "yam_ql"],
  [/Yamaha DM7/i, "yam_dm7"],
  [/Yamaha DM3/i, "yam_dm3"],
  [/Yamaha TF/i, "yam_tf"],
  [/Yamaha (RPio|Rio)/i, "yam_rio"],
  [/Yamaha Tio/i, "yam_tio"],
  [/Yamaha Ri8/i, "yam_ri8"],
  [/Yamaha RUio/i, "yam_ruio"],
  [/Yamaha .*(NY64|HY\d|AIC128)/i, "dante_karte"],
  [/Yamaha .*(XMV|PC-D|NXAMP)/i, "yam_amp"],
  [/Yamaha (MTX|MRX|DME)/i, "yam_dsp"],
  [/Yamaha SWP/i, "yam_swp"],
  [/Yamaha SW[RX]/i, "yam_switch"],
  // Schnick-Schnack-Systems
  [/Schnick.*DPB/i, "sss_dpb"],
  [/Schnick.*Pixel-Gate/i, "sss_pixelgate"],
  [/Schnick.*Systemnetzteil/i, "sss_netzteil"],
  [/Schnick.*Sys One/i, "sss_sysone"],
  [/Schnick.*LED-Tile D50/i, "sss_tile"],
  [/Schnick.*LED-Strips/i, "sss_strip"],
  // Audinate / Dante
  [/AVIO USB/i, "dante_avio_usb"],
  [/AVIO Bluetooth/i, "dante_avio_bt"],
  [/AVIO/i, "dante_avio_xlr"],
  [/Dante-MY16|Dante PCIe/i, "dante_karte"],
  [/Brooklyn|Broadway|Ultimo|Dante IP Core|Dante Embedded/i, "dante_modul"],
];

// Katalog-Rohdaten (Hersteller/Modell) → Icon-Schlüssel oder null
export const modellIcon = (hersteller, modell) => {
  const s = `${hersteller || ""} ${modell || ""}`;
  for (const [re, icon] of REGELN) if (re.test(s)) return icon;
  return null;
};
