/* Modell-Icons der Fokus-Hersteller: welches Katalog-Gerät welches Icon bekommt.
   Die SVGs liegen in assets/icons/devices und werden mit
   scripts/geraete-icons.js erzeugt. Die Regeln prüfen „Hersteller Modell“ von
   oben nach unten, die erste passende gewinnt. Geräte ohne Treffer behalten
   das Icon ihres Gerätetyps. */

export const MODELL_ICONS = {
  // key: [Hersteller, Bezeichnung im Icon-Auswahlmenü]
  ma3_full: ["MA Lighting", "grandMA3 full-size"],
  ma3_light: ["MA Lighting", "grandMA3 light"],
  ma3_compact_xt: ["MA Lighting", "grandMA3 compact XT"],
  ma3_compact: ["MA Lighting", "grandMA3 compact"],
  ma3_extension: ["MA Lighting", "grandMA3 extension"],
  ma3_replay: ["MA Lighting", "grandMA3 replay unit"],
  ma3_pu_m: ["MA Lighting", "grandMA3 processing unit M"],
  ma3_pu_l: ["MA Lighting", "grandMA3 processing unit L"],
  ma3_pu_xl: ["MA Lighting", "grandMA3 processing unit XL"],
  ma3_cmdwing_xt: ["MA Lighting", "grandMA3 command wing XT"],
  ma3_cmdwing: ["MA Lighting", "grandMA3 command wing"],
  ma3_faderwing: ["MA Lighting", "grandMA3 fader wing"],
  ma3_node2: ["MA Lighting", "grandMA3 2Port Node"],
  ma3_node4: ["MA Lighting", "grandMA3 4Port Node"],
  ma3_node8: ["MA Lighting", "grandMA3 8Port Node"],
  ma3_ionode: ["MA Lighting", "grandMA3 I/O Node"],
  ma_switch: ["MA Lighting", "MA Network Switch"],
  ma2_full: ["MA Lighting", "grandMA2 full-size"],
  ma2_light: ["MA Lighting", "grandMA2 light"],
  ma2_ultralight: ["MA Lighting", "grandMA2 ultra-light"],
  ma2_replay: ["MA Lighting", "grandMA2 replay unit"],
  ma2_cmdwing: ["MA Lighting", "grandMA2 command wing"],
  ma2_faderwing: ["MA Lighting", "grandMA2 fader wing"],
  ma2_node2: ["MA Lighting", "MA 2Port Node (grandMA2)"],
  ma2_node8: ["MA Lighting", "MA 4Port / 8Port Node (grandMA2)"],
  ma_npu: ["MA Lighting", "MA NPU"],
  ma_vpu: ["MA Lighting", "MA VPU"],
  ma_nsp: ["MA Lighting", "MA NSP"],
  ma1: ["MA Lighting", "grandMA (1)"],
  dot2_core: ["MA Lighting", "dot2 core"],
  dot2_wing: ["MA Lighting", "dot2 XL / Wing"],
  dot2_node4: ["MA Lighting", "dot2 Node4"],
  gc10: ["Luminex", "GigaCore 10"],
  gc16: ["Luminex", "GigaCore 12 / 14 / 16"],
  gc18: ["Luminex", "GigaCore 18t / 20t"],
  gc30: ["Luminex", "GigaCore 26i / 30i"],
  luminode1: ["Luminex", "LumiNode 1"],
  luminode2: ["Luminex", "LumiNode 2"],
  luminode4: ["Luminex", "LumiNode 4"],
  luminode12: ["Luminex", "LumiNode 12"],
  lumicore: ["Luminex", "LumiCore"],
  lumisplit: ["Luminex", "LumiSplit"],
  cisco_8: ["Cisco", "Switch 8 Ports (kompakt)"],
  cisco_16: ["Cisco", "Switch 16 Ports"],
  cisco_24: ["Cisco", "Switch 24 Ports"],
  cisco_48: ["Cisco", "Switch 48 Ports"],
  cisco_c1300_24p4x: ["Cisco", "Catalyst C1300-24P-4X"],
  cisco_9k: ["Cisco", "Catalyst 9200 / 9300"],
  cisco_meraki: ["Cisco", "Meraki MS"],
  cisco_ie: ["Cisco", "Catalyst IE (Hutschiene)"],
  cisco_ap: ["Cisco", "Access Point"],
  yam_rivage: ["Yamaha", "RIVAGE PM"],
  yam_cl: ["Yamaha", "CL5 / CL3 / CL1"],
  yam_ql: ["Yamaha", "QL5 / QL1"],
  yam_dm7: ["Yamaha", "DM7"],
  yam_dm3: ["Yamaha", "DM3"],
  yam_tf: ["Yamaha", "TF-Serie"],
  yam_rio: ["Yamaha", "Rio / RPio / RSio"],
  yam_tio: ["Yamaha", "Tio1608"],
  yam_ri8: ["Yamaha", "Ri8-D / Ro8-D"],
  yam_ruio: ["Yamaha", "RUio16-D"],
  yam_amp: ["Yamaha", "Endstufe (XMV, PC, NXAMP)"],
  yam_dsp: ["Yamaha", "DSP (MTX, MRX, DME)"],
  yam_swp: ["Yamaha", "SWP1 / SWP2"],
  yam_switch: ["Yamaha", "SWR / SWX"],
  sss_dpb: ["Schnick-Schnack-Systems", "DPB Pixel-Router"],
  sss_pixelgate: ["Schnick-Schnack-Systems", "Pixel-Gate"],
  sss_netzteil: ["Schnick-Schnack-Systems", "Systemnetzteil 4 / 4E"],
  sss_sysone: ["Schnick-Schnack-Systems", "Sys One"],
  sss_tile: ["Schnick-Schnack-Systems", "LED-Tile"],
  sss_strip: ["Schnick-Schnack-Systems", "LED-Strip / Profil"],
  dante_avio_xlr: ["Audinate", "Dante AVIO (XLR / AES3)"],
  dante_avio_usb: ["Audinate", "Dante AVIO USB"],
  dante_avio_bt: ["Audinate", "Dante AVIO Bluetooth"],
  dante_karte: ["Audinate", "Dante-Karte (Slot / PCIe)"],
  dante_modul: ["Audinate", "Dante-OEM-Modul"],
  // Aussteller LEaT con 26
  ah_sq: ["Allen & Heath", "SQ-5 / SQ-6"],
  ah_avantis: ["Allen & Heath", "Avantis Solo"],
  ah_mixrack: ["Allen & Heath", "dLive MixRack (CDM / DM)"],
  ah_ahm: ["Allen & Heath", "AHM-Serie"],
  ah_expander: ["Allen & Heath", "DT168 / DT164-W"],
  ah_ip: ["Allen & Heath", "IP6 / IP8"],
  avid_s6l: ["Avid", "VENUE S6L"],
  avid_engine: ["Avid", "VENUE E6L"],
  avid_stage: ["Avid", "VENUE Stage 64 / 32 / 16"],
  at_cdj: ["AlphaTheta", "CDJ"],
  at_djm: ["AlphaTheta", "DJM"],
  at_xdj: ["AlphaTheta", "XDJ-AZ"],
  biamp_tesira: ["Biamp", "Tesira"],
  brompton_proc: ["Brompton Technology", "Tessera S8 / SQ200"],
  brompton_xd: ["Brompton Technology", "Tessera XD / QD"],
  barco_s3: ["Barco", "Event Master S3 / ImagePRO"],
  barco_ec: ["Barco", "Event Master EC-210"],
  pixera: ["AV Stumpfl", "PIXERA"],
  canon_ptz: ["Canon", "PTZ-Kamera (CR-N / CR-X)"],
  aver_ptz: ["AVer", "PTZ-Kamera"],
  tricaster: ["Vizrt", "TriCaster"],
  crestron_nvx: ["Crestron", "DM NVX"],
  blustream_ip: ["Blustream", "IP-Encoder / Decoder"],
  adder_alif: ["Adder", "ADDERLink INFINITY"],
  digitus_24: ["DIGITUS by ASSMANN", "Switch 24 Ports"],
  avo_diamond: ["Avolites", "Diamond 9 / 7"],
  avo_sapphire: ["Avolites", "Sapphire Touch"],
  avo_tnp: ["Avolites", "Titan Net Processor"],
  adj_net: ["ADJ Lighting", "NET 4 / NET 8"],
  astera_netbox: ["Astera LED Technology", "NetBox"],
  bose_amp: ["Bose Professional", "PowerShare / PowerSpace"],
  db_amp: ["d&b audiotechnik", "Verstärker (D-Serie, 5D–40D)"],
  db_ds100: ["d&b audiotechnik", "DS100"],
  dad_ax: ["DAD (Digital Audio Denmark)", "AX64 / AX32 / CORE"],
  chauvet_netx: ["Chauvet Professional", "Net-X II"],
  coda_linus: ["CODA Audio", "LINUS-Verstärker"],
  colorlight_proc: ["Colorlight", "LED-Prozessor"],
  genelec_ip: ["Genelec", "Smart IP"],
  lautsprecher_array: ["Lautsprecher", "Line-Array-Element (Netzwerk)"],
  lautsprecher_sub: ["Lautsprecher", "Subwoofer (Netzwerk)"],
  digico_s: ["DiGiCo", "S21 / S31"],
  digico_q: ["DiGiCo", "Quantum"],
  digico_rack: ["DiGiCo", "Stagebox (Rack)"],
  waves_server: ["Waves Audio", "SoundGrid Server"],
  digigrid_io: ["Waves Audio", "DiGiGrid I/O"],
  hippotizer: ["Green Hippo", "Hippotizer"],
  matrox_ip: ["Matrox Video", "ConvertIP / Monarch EDGE"],
  directout_prodigy: ["DirectOut", "PRODIGY"],
  amp_4k: ["Endstufen", "4-Kanal-Endstufe (Netzwerk, 2 HE)"],
  inst_1he: ["Installation", "Installationsverstärker / DSP (1 HE)"],
  wandpanel: ["Installation", "Dante-Wandpanel"],
};

const REGELN = [
  // MA Lighting — grandMA3
  [/grandMA3 full-size/i, "ma3_full"],
  [/grandMA3 light/i, "ma3_light"],
  [/grandMA3 compact XT/i, "ma3_compact_xt"],
  [/grandMA3 compact/i, "ma3_compact"],
  [/grandMA3 extension/i, "ma3_extension"],
  [/grandMA3 replay/i, "ma3_replay"],
  [/grandMA3 processing unit XL/i, "ma3_pu_xl"],
  [/grandMA3 processing unit L/i, "ma3_pu_l"],
  [/grandMA3 processing unit M/i, "ma3_pu_m"],
  [/grandMA3 onPC command wing XT/i, "ma3_cmdwing_xt"],
  [/grandMA3 onPC command wing/i, "ma3_cmdwing"],
  [/grandMA3 onPC fader wing/i, "ma3_faderwing"],
  [/grandMA3 I\/O Node/i, "ma3_ionode"],
  [/grandMA3 .*\b2Port Node/i, "ma3_node2"],
  [/grandMA3 .*\b8Port Node/i, "ma3_node8"],
  [/grandMA3 .*\b4Port Node|grandMA3 xPort/i, "ma3_node4"],
  [/MA Network Switch/i, "ma_switch"],
  // grandMA2 und MA-Netzwerkgeräte
  [/grandMA2 full-size/i, "ma2_full"],
  [/grandMA2 light/i, "ma2_light"],
  [/grandMA2 ultra-light/i, "ma2_ultralight"],
  [/grandMA2 replay/i, "ma2_replay"],
  [/grandMA2 onPC command wing/i, "ma2_cmdwing"],
  [/grandMA2 fader wing/i, "ma2_faderwing"],
  [/MA NPU/i, "ma_npu"],
  [/MA VPU/i, "ma_vpu"],
  [/MA NSP/i, "ma_nsp"],
  [/MA Lighting MA 2Port Node/i, "ma2_node2"],
  [/MA Lighting MA [48]Port Node/i, "ma2_node8"],
  [/grandMA1|grandMA \(grandMA1\)/i, "ma1"],
  [/dot2 core/i, "dot2_core"],
  [/dot2 XL|dot2 .*wing/i, "dot2_wing"],
  [/dot2 Node4/i, "dot2_node4"],
  // Luminex
  [/GigaCore 10\b|GigaCore 10[it]/i, "gc10"],
  [/GigaCore 1[2-6]|GigaCore 14R/i, "gc16"],
  [/GigaCore (18|20)/i, "gc18"],
  [/GigaCore (26|30)/i, "gc30"],
  [/LumiNode 12/i, "luminode12"],
  [/LumiNode 4/i, "luminode4"],
  [/LumiNode 2|Ethernet-DMX2/i, "luminode2"],
  [/LumiNode 1/i, "luminode1"],
  [/Ethernet-DMX8/i, "luminode12"],
  [/LumiCore/i, "lumicore"],
  [/LumiSplit/i, "lumisplit"],
  // Cisco
  [/Cisco .*Meraki MS/i, "cisco_meraki"],
  [/Cisco .*(9120|Meraki MR)/i, "cisco_ap"],
  [/Cisco .*IE3300/i, "cisco_ie"],
  [/Cisco Catalyst 9[23]00/i, "cisco_9k"],
  [/Cisco .*-(8|10)[A-Z]*P?-|SG350-10|Cisco .*-8[A-Z]{1,3}-|C1300-12XT|2960-L/i, "cisco_8"],
  [/C1300X?-24F?P-4X/i, "cisco_c1300_24p4x"],
  [/Cisco .*-16/i, "cisco_16"],
  [/Cisco .*-(24|28)|Cisco .*SG350-28/i, "cisco_24"],
  [/Cisco .*-48/i, "cisco_48"],
  // Yamaha (auch NEXO)
  [/^Yamaha RIVAGE/i, "yam_rivage"],
  [/Yamaha CL5/i, "yam_cl"],
  [/Yamaha QL/i, "yam_ql"],
  [/Yamaha DM7/i, "yam_dm7"],
  [/Yamaha DM3/i, "yam_dm3"],
  [/Yamaha TF/i, "yam_tf"],
  [/Yamaha (RPio|RSio|Rio)/i, "yam_rio"],
  [/Yamaha Tio/i, "yam_tio"],
  [/Yamaha Ri8/i, "yam_ri8"],
  [/Yamaha RUio/i, "yam_ruio"],
  [/Yamaha .*(NY64|HY\d|AIC128)/i, "dante_karte"],
  [/Yamaha .*(XMV|PC-D|NXAMP)/i, "yam_amp"],
  [/Yamaha (MTX|MRX|DME)/i, "yam_dsp"],
  [/Yamaha SWP/i, "yam_swp"],
  [/Yamaha SW[RX]/i, "yam_switch"],
  // Schnick-Schnack-Systems
  [/Schnick.*DPB/i, "sss_dpb"],
  [/Schnick.*Pixel-Gate/i, "sss_pixelgate"],
  [/Schnick.*Systemnetzteil/i, "sss_netzteil"],
  [/Schnick.*Sys One/i, "sss_sysone"],
  [/Schnick.*LED-Tile D50/i, "sss_tile"],
  [/Schnick.*LED-Strips/i, "sss_strip"],
  // Audinate / Dante
  [/AVIO USB/i, "dante_avio_usb"],
  [/AVIO Bluetooth/i, "dante_avio_bt"],
  [/AVIO/i, "dante_avio_xlr"],
  [/Dante-MY16|Dante PCIe/i, "dante_karte"],
  [/Brooklyn|Broadway|Ultimo|Dante IP Core|Dante Embedded/i, "dante_modul"],
  // Aussteller LEaT con 26
  [/^Allen & Heath SQ-/i, "ah_sq"],
  [/^Allen & Heath Avantis/i, "ah_avantis"],
  [/^Allen & Heath dLive (CDM|DM)/i, "ah_mixrack"],
  [/^Allen & Heath AHM/i, "ah_ahm"],
  [/^Allen & Heath DT16/i, "ah_expander"],
  [/^Allen & Heath IP\d/i, "ah_ip"],
  [/^Avid VENUE S6L/i, "avid_s6l"],
  [/^Avid VENUE E6L/i, "avid_engine"],
  [/^Avid VENUE (Stage|Local)/i, "avid_stage"],
  [/^AlphaTheta CDJ/i, "at_cdj"],
  [/^AlphaTheta DJM/i, "at_djm"],
  [/^AlphaTheta XDJ/i, "at_xdj"],
  [/^Biamp Tesira/i, "biamp_tesira"],
  [/^Brompton Technology Tessera (S8|SQ200|SX40)/i, "brompton_proc"],
  [/^Brompton Technology Tessera (XD|QD)/i, "brompton_xd"],
  [/^Barco (Event Master S3|ImagePRO)/i, "barco_s3"],
  [/^Barco EC-/i, "barco_ec"],
  [/^AV Stumpfl PIXERA/i, "pixera"],
  [/^Canon CR-/i, "canon_ptz"],
  [/^AVer (PTZ|TR)\d/i, "aver_ptz"],
  [/^Vizrt TriCaster/i, "tricaster"],
  [/^Crestron DM-NVX/i, "crestron_nvx"],
  [/^Blustream IP\d/i, "blustream_ip"],
  [/^Adder ADDERLink INFINITY \d/i, "adder_alif"],
  [/^DIGITUS.*24-Port/i, "digitus_24"],
  [/^Avolites Diamond/i, "avo_diamond"],
  [/^Avolites Sapphire/i, "avo_sapphire"],
  [/^Avolites Titan Net Processor/i, "avo_tnp"],
  [/^ADJ Lighting NET \d/i, "adj_net"],
  [/^Astera .*NetBox/i, "astera_netbox"],
  [/^Bose Professional Power(Share|Space)/i, "bose_amp"],
  [/^d&b audiotechnik (D80|D90|D40|40D|5D|10D|30D)\b/i, "db_amp"],
  [/^d&b audiotechnik DS100/i, "db_ds100"],
  [/^DAD .*(AX64|AX32|AX Center|CORE 256)/i, "dad_ax"],
  [/^Chauvet Professional Net-X/i, "chauvet_netx"],
  [/^CODA Audio LINUS/i, "coda_linus"],
  [/^Colorlight /i, "colorlight_proc"],
  [/^Genelec Smart IP/i, "genelec_ip"],
  [/^(HK Audio .*(Sub|SUB)|ADAMSON CS11[89]|FBT Elettronica MUSE (118|218))/i, "lautsprecher_sub"],
  [/^(HK Audio LINEAR .*LTA|ADAMSON (CS10|CS7|VG))/i, "lautsprecher_array"],
  [/^DiGiCo (S21|S31)/i, "digico_s"],
  [/^DiGiCo Quantum/i, "digico_q"],
  [/^DiGiCo .*Rack/i, "digico_rack"],
  [/^Waves Audio .*SoundGrid Server/i, "waves_server"],
  [/^(Waves Audio DiGiGrid|DiGiGrid) /i, "digigrid_io"],
  [/^Green Hippo Hippotizer/i, "hippotizer"],
  [/^Matrox Video (ConvertIP|Monarch EDGE)/i, "matrox_ip"],
  [/^DirectOut PRODIGY/i, "directout_prodigy"],
  [/^(Dynacord (IPX|TGX)|Fohhn Audio DI-|Martin Audio iKON|FBT Elettronica TALOS|ADAMSON XG)/i, "amp_4k"],
  [/^(DAS Audio INTEGRAL-MA|AUDAC AMP|ECLER eCA|Fohhn Audio MA-|MONACOR PA-)/i, "inst_1he"],
  [/^(AUDAC NWP|MONACOR (DADC|ADP-DAI))/i, "wandpanel"],
];

// Katalog-Rohdaten (Hersteller/Modell) → Icon-Schlüssel oder null
export const modellIcon = (hersteller, modell) => {
  const s = `${hersteller || ""} ${modell || ""}`;
  for (const [re, icon] of REGELN) if (re.test(s)) return icon;
  return null;
};
